# Changes to workflow name require changes to badge URL in README.md
name: E2E Tests

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "**.md"

  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  cypress-run:
    # Platform recommended in cypress-io/github-action docs.
    runs-on: ubuntu-16.04
    # Manually skip this 10+ minute build based on commit message.
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      # Use native docker command within docker-compose
      COMPOSE_DOCKER_CLI_BUILD: 1
      # Use buildkit to speed up docker command
      DOCKER_BUILDKIT: 1
    steps:
      # This ensures only the most recently push commit will keep running.
      - name: Cancel other active runs of this workflow
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Enable comment translation
        # If we're in a pull_request from a main repo branch, NOT a fork.
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: |
          echo GOOGLE_CREDENTIALS_BASE64=${{ secrets.GOOGLE_CREDENTIALS_BASE64 }} > server/docker-dev.env
          echo SHOULD_USE_TRANSLATION_API=true > server/docker-dev.env

      - name: Serve app via docker-compose
        run: docker-compose up --detach

      - name: Run Cypress tests: default
        uses: cypress-io/github-action@v1
        env:
          CYPRESS_BASE_URL: http://localhost
        with:
          working-directory: ./e2e
          spec: cypress/integration/polis/**/*.spec.js
          config: ignoreTestFiles='**/polis/**/comment-translation.spec.js'
          browser: chrome

      - name: Run Cypress tests: comment translation
        # If we're in a pull_request from a main repo branch, NOT a fork.
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: cypress-io/github-action@v1
        env:
          CYPRESS_BASE_URL: http://localhost
        with:
          working-directory: ./e2e
          spec: cypress/integration/polis/**/comment-translation.spec.js
          browser: chrome

      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      - name: Save screenshot artefacts
        uses: actions/upload-artifact@v2.0.1
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots

      # Test run video was always captured, so this action uses "always()" condition
      - name: Save video artefacts
        uses: actions/upload-artifact@v2.0.1
        if: always()
        with:
          name: cypress-videos
          path: e2e/cypress/videos
